cookie:
  expiry_days: 30
  key: some_random_key_123
  name: some_random_cookie
credentials:
  usernames:
    harshu:
      email: harsha@gmail.com
      failed_login_attempts: 0
      first_name: harsha
      last_name: sree
      logged_in: true
      password: $2b$12$ylIQ0fmIvLwPg30cIzKM2.i8tpY/b5HGxvYzw/lV3dqHzk.cbH3qK
      password_hint: name
      roles:
      - admin
    sr_123:
      email: srujan1@gamil.com
      failed_login_attempts: 0
      first_name: srujan
      last_name: Manukonda
      logged_in: true
      password: $2b$12$mNFX0JwfnvCLndRc1iMh/.UeK/aS5b0RjapkH0cZOvcmvZDA.vl0e
      password_hint: name
      roles:
      - user
    sru_123:
      email: srujan@gmail.com
      failed_login_attempts: 2
      first_name: Srujan
      last_name: sai
      logged_in: true
      password: $2b$12$1aT6aXM/Sk8nOOFjHoz4yu2TW2OLnAqzmb.3w.BfV0w61ffCd2rIS
      password_hint: name
      roles:
      - user
    sru_321:
      email: srujan10@gmail.com
      failed_login_attempts: 0
      first_name: Srujan
      last_name: Manukonda
      logged_in: true
      password: $2b$12$r9VI7tp37FAloeaK54kV3etVPu4Wf0GFE.dja2Hhy8Li09XTyB.wG
      password_hint: name
      roles:
      - admin
preauthorized:
  emails: []
